[2025-10-02 03:00:56] INFO root: init_logging: logfile=logs\log_20251002_010056.txt
[2025-10-02 03:00:56] INFO __main__: Logging initialized
[2025-10-02 03:00:58] INFO root: Config loaded from config\gui_config.json
[2025-10-02 03:03:02] CRITICAL root: Uncaught exception
Traceback (most recent call last):
  File "C:\Users\soyko\Documents\git2\Market\project assistant\env.model_0.9\0.9f\fibopkg5\trading_gui_extended.py", line 3044, in <module>
    main()
  File "C:\Users\soyko\Documents\git2\Market\project assistant\env.model_0.9\0.9f\fibopkg5\trading_gui_extended.py", line 3040, in main
    root.mainloop()
  File "C:\Users\soyko\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1458, in mainloop
    self.tk.mainloop(n)
KeyboardInterrupt
