[2025-10-02 17:08:55] INFO root: init_logging: logfile=logs\log_20251002_150855.txt
[2025-10-02 17:08:55] INFO __main__: Logging initialized
[2025-10-02 17:09:04] INFO root: Config loaded from config\gui_config.json
[2025-10-02 17:09:04] ERROR __main__: DB writer failed to start
Traceback (most recent call last):
  File "C:\Users\aladin\Documents\github\cow-lvl\tradeapp.py", line 1018, in _db_writer_loop
    conn = sqlite3.connect(str(db_path), check_same_thread=True, timeout=5.0)
sqlite3.OperationalError: unable to open database file
[2025-10-02 17:09:04] ERROR root: DB writer failed to start:
Traceback (most recent call last):
  File "C:\Users\aladin\Documents\github\cow-lvl\tradeapp.py", line 1018, in _db_writer_loop
    conn = sqlite3.connect(str(db_path), check_same_thread=True, timeout=5.0)
sqlite3.OperationalError: unable to open database file

[2025-10-02 17:09:56] INFO root: Preview loaded: 200 rows.
[2025-10-02 17:10:12] INFO root: Preview loaded: 200 rows.
