[2025-10-01 00:13:06] INFO root: init_logging: logfile=logs\log_20250930_221306.txt
[2025-10-01 00:13:06] INFO __main__: Logging initialized
[2025-10-01 00:13:09] INFO root: Config loaded from config\gui_config.json
[2025-10-01 00:13:25] INFO root: Preview loaded: 200 rows.
[2025-10-01 00:13:28] INFO root: Preview loaded: 200 rows.
[2025-10-01 00:13:32] INFO root: Prepare: loading data from sqlite...
[2025-10-01 00:13:32] INFO root: Prepare thread started.
[2025-10-01 00:13:32] INFO root: Loaded 106175 rows from sqlite.
[2025-10-01 00:13:33] INFO root: Computed features. Shape: (106175, 49)
[2025-10-01 00:13:33] INFO root: dropna: before=106175, after=0, removed=106175
[2025-10-01 00:13:33] INFO root: No numeric feature columns detected after cleaning. Abort.
[2025-10-01 00:19:46] CRITICAL root: Uncaught exception
Traceback (most recent call last):
  File "C:\Users\soyko\Documents\git2\Market\project assistant\env.model_0.9\0.9f\fibopkg5\trading_gui_extended.py", line 2697, in <module>
    main()
  File "C:\Users\soyko\Documents\git2\Market\project assistant\env.model_0.9\0.9f\fibopkg5\trading_gui_extended.py", line 2693, in main
    root.mainloop()
  File "C:\Users\soyko\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1458, in mainloop
    self.tk.mainloop(n)
KeyboardInterrupt
